[[Plant]]
Name = "Marigold"
Ref-Sprite-Sprite = "Marigold"
GrowthTimeSecs = 45
FootprintSize = { Width = 1.0, Height = 1.0 }
# TODO: How to handle growth condition?

[[Plant]]
Name = "Reeds"
Ref-Sprite-Sprite = "Reeds"
GrowthTimeSecs = 30
FootprintSize = { Width = 1.0, Height = 1.0 }

[[Plant]]
Name = "GreatOak"
Ref-Sprite-Sprite = "GreatTree"
GrowthTimeSecs = 0
FootprintSize = { Width = 3.0, Height = 3.0 }
CollisionFootprint = { X = 0.0, Y = 0.0, Width = 3.0, Height = 3.0 }
Tag = "GreatTree"