[[Sprite]]
Name = "Player"
Path = "sprites/gnome"
Origin = { X = 16, Y = 32 }

[[Sprite]]
Name = "Inchworm"
Path = "sprites/units/inchworm"

[[Sprite]]
Name = "ValidTile"
Path = "sprites/valid_square"
Origin = { X = 16 }

[[Sprite]]
Name = "SelectedTileOverlay"
Path = "tilesets/selected_overlay"
Origin = { X = 16 }

[[Sprite]]
Name = "LoadingBarEmpty"
Path = "sprites/loading_bar"
AtlasRect = { Width = 24, Height = 3 }

[[Sprite]]
Name = "LoadingBarFull"
Path = "sprites/loading_bar"
AtlasRect = { Y = 3, Width = 24, Height = 3 }

[[Sprite]]
Name = "InventoryContainer"
Path = "sprites/inventory_border"

[[Sprite]]
Name = "InventorySelected"
Path = "sprites/inventory_selected"

[[Sprite]]
Name = "GreatTree"
Path = "sprites/plants/great_tree"

[[Sprite]]
Name = "Marigold"
Path = "sprites/plants/marigold"
Origin = { X = 16, Y = 32 }

[[Sprite]]
Name = "Reeds"
Path = "sprites/plants/reeds"
Origin = { X = 16, Y = 32 }

[[Sprite]]
Name = "Dandelion"
Path = "sprites/plants/dandelion"
Origin = { X = 16, Y = 32 }

[[Sprite]]
Name = "Shrub"
Path = "sprites/plants/shrub"
Origin = { X = 16, Y = 32 }

[[Sprite]]
Name = "Water0"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 0, Width = 32, Height = 16 }

[[Sprite]]
Name = "Water1"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 32, Width = 32, Height = 16 }

[[Sprite]]
Name = "Water2Nw"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 64, Width = 32, Height = 16 }

[[Sprite]]
Name = "Water2Sw"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 96, Width = 32, Height = 16 }

[[Sprite]]
Name = "Water2Ew"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 128, Width = 32, Height = 16 }

[[Sprite]]
Name = "Water3"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 160, Width = 32, Height = 16 }

[[Sprite]]
Name = "Water4"
Path = "tilesets/water"
Origin = { X = 16, Y = 0 }
AtlasRect = { X = 192, Width = 32, Height = 16 }

[[Sprite]]
Name = "Weeds1"
Path = "tilesets/grass"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 0, Width = 32, Height = 24 }

[[Sprite]]
Name = "Weeds2"
Path = "tilesets/grass"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 32, Width = 32, Height = 24 }

[[Sprite]]
Name = "Weeds3"
Path = "tilesets/grass"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 64, Width = 32, Height = 24 }

[[Sprite]]
Name = "Sand1"
Path = "tilesets/sand"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 0, Width = 32, Height = 24 }

[[Sprite]]
Name = "Sand2"
Path = "tilesets/sand"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 32, Width = 32, Height = 24 }

[[Sprite]]
Name = "Sand3"
Path = "tilesets/sand"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 64, Width = 32, Height = 24 }

[[Sprite]]
Name = "Rocks1"
Path = "tilesets/rocks"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 0, Width = 32, Height = 24 }

[[Sprite]]
Name = "Rocks2"
Path = "tilesets/rocks"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 32, Width = 32, Height = 24 }

[[Sprite]]
Name = "Rocks3"
Path = "tilesets/rocks"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 64, Width = 32, Height = 24 }

[[Sprite]]
Name = "DryDirt1"
Path = "tilesets/dry_dirt"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 0, Width = 32, Height = 24 }

[[Sprite]]
Name = "DryDirt2"
Path = "tilesets/dry_dirt"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 32, Width = 32, Height = 24 }

[[Sprite]]
Name = "DryDirt3"
Path = "tilesets/dry_dirt"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 64, Width = 32, Height = 24 }

[[Sprite]]
Name = "FlowerPatch1"
Path = "tilesets/flower_patch"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 0, Width = 32, Height = 24 }

[[Sprite]]
Name = "FlowerPatch2"
Path = "tilesets/flower_patch"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 32, Width = 32, Height = 24 }

[[Sprite]]
Name = "FlowerPatch3"
Path = "tilesets/flower_patch"
Origin = { X = 16, Y = 8 }
AtlasRect = { X = 64, Width = 32, Height = 24 }

[[Sprite]]
Name = "InventoryReedSeeds"
Path = "sprites/inventory_items"
AtlasRect = { X = 0, Y = 0, Width = 16, Height = 16 }

[[Sprite]]
Name = "InventoryGreatAcorn"
Path = "sprites/inventory_items"
AtlasRect = { X = 16, Y = 0, Width = 16, Height = 16 }

[[Sprite]]
Name = "HandTool"
Path = "sprites/tools"
AtlasRect = { Width = 16, Height = 16 }

[[Sprite]]
Name = "TillerTool"
Path = "sprites/tools"
AtlasRect = { X = 16, Width = 16, Height = 16 }

[[Sprite]]
Name = "ShovelTool"
Path = "sprites/tools"
AtlasRect = { X = 32, Width = 16, Height = 16 }

[[Sprite]]
Name = "ProgressBarFillEmpty"
Path = "sprites/progress_bar_fill"
AtlasRect = { X = 0, Width = 2, Height = 1 }

[[Sprite]]
Name = "ProgressBarFillHp"
Path = "sprites/progress_bar_fill"
AtlasRect = { X = 2, Width = 2, Height = 1 }

[[Sprite]]
Name = "ProgressBarFillEnergy"
Path = "sprites/progress_bar_fill"
AtlasRect = { X = 4, Width = 2, Height = 1 }
