[[Unit]]
Name = "Inchworm"
Ref-Sprite-Sprite = "Inchworm"
CollisionFootprint = { X = -0.25, Y = -0.25, Width = 0.5, Height = 0.5 }
Hp = 25
SpeedTilesPerSec = 0.75
AttackRange = 0.25
AggroRange = 5.0
Ref-EnemyAiState-InitalBehavior = "AttackTree"