[[Foo]]
Name = "Bar"
A = 1.3
B = 3
D = { X = 3, Y = 4 }

[[Foo]]
Name = "Hello"
C = [42, 67]
B = 2

[[Foo]]
Name = "World"
A = 5.0
C = [5, 6, 7]
Ref-Bar-ThisIsABar = "SomethingElse"

[[Foo]]
Name = "Xyz"
D = { X = 500, Y = 80, Z = 20 }