using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Engine.Vars;

[Generator]
public class VarsSourceGenerator : ISourceGenerator {
  private const string Namespace = "Engine.Vars.Generated";
  
  public void Initialize(GeneratorInitializationContext context) {}

  public void Execute(GeneratorExecutionContext context) {
    foreach (var file in context.AdditionalFiles) {
      var fileName = Path.GetFileNameWithoutExtension(file.Path);
      WriteTestClass(fileName, context);
    }
  }

  private void WriteTestClass(string name, GeneratorExecutionContext context) {
    var code = new StringBuilder("// <auto-generated/>\n");
    code.AppendLine("using System;");
    code.AppendLine($"namespace {Namespace} {{");
    code.AppendLine($"public partial class {name} {{");
    code.AppendLine("  public static void test() {}");
    code.AppendLine("}}");
    
    context.AddSource(
        $"{name}.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
  }
}